language: scala

jdk: oraclejdk8

matrix:
  include:
    - scala: 2.10.6
      env: TRAVIS_SBT_VERSION="0.13.16"
    - scala: 2.12.3
      env: TRAVIS_SBT_VERSION="1.0.0"

sudo: false

# build with coverage
script:
  - sbt ^test

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache